# Generated by Django 6.0.2 on 2026-03-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
