# Generated by Django 6.0.2 on 2026-03-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
