# Generated by Django 6.0.2 on 2026-04-20

import app.service.UploadService
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsimage",
            name="image",
            field=models.ImageField(upload_to=app.service.UploadService.news_image_upload_to),
        ),
    ]

