# Generated by Django 6.0.2 on 2026-03-18 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('print_3d', 'Impressão 3D'), ('modeling', 'Modelagem'), ('hardware', 'Hardware'), ('software', 'Software')], max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_creators', models.ManyToManyField(blank=True, related_name='co_created_projects', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Print3DData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('weight_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('print_time', models.DurationField(blank=True, help_text='Formato: HH:MM:SS', null=True)),
                ('project', models.OneToOneField(limit_choices_to={'project_type': 'print_3d'}, on_delete=django.db.models.deletion.CASCADE, related_name='print_3d_data', to='projects.project')),
            ],
            options={
                'verbose_name': 'Dados de Impressão 3D',
                'verbose_name_plural': 'Dados de Impressão 3D',
            },
        ),
        migrations.CreateModel(
            name='Project3DFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='projects/3d_files/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_3d', to='projects.project')),
            ],
            options={
                'verbose_name': 'Arquivo 3D do Projeto',
                'verbose_name_plural': 'Arquivos 3D do Projeto',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'verbose_name': 'Imagem do Projeto',
                'verbose_name_plural': 'Imagens do Projeto',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='projects.project')),
            ],
            options={
                'verbose_name': 'Vídeo do Projeto',
                'verbose_name_plural': 'Vídeos do Projeto',
            },
        ),
        migrations.CreateModel(
            name='PrintStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_steps', to='projects.project')),
            ],
            options={
                'verbose_name': 'Etapa de Impressão',
                'verbose_name_plural': 'Etapas de Impressão',
                'ordering': ['step_number'],
                'unique_together': {('project', 'step_number')},
            },
        ),
    ]
