# Generated by Django 6.0.2 on 2026-03-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Print3DData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('weight_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('print_time', models.DurationField(blank=True, help_text='Formato: HH:MM:SS', null=True)),
            ],
            options={
                'verbose_name': 'Dados de Impressão 3D',
                'verbose_name_plural': 'Dados de Impressão 3D',
            },
        ),
        migrations.CreateModel(
            name='PrintStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Etapa de Impressão',
                'verbose_name_plural': 'Etapas de Impressão',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('print_3d', 'Impressão 3D'), ('modeling', 'Modelagem'), ('hardware', 'Hardware'), ('software', 'Software')], max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project3DFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='projects/3d_files/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Arquivo 3D do Projeto',
                'verbose_name_plural': 'Arquivos 3D do Projeto',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Imagem do Projeto',
                'verbose_name_plural': 'Imagens do Projeto',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Vídeo do Projeto',
                'verbose_name_plural': 'Vídeos do Projeto',
            },
        ),
    ]
