# Generated by Django 6.0.2 on 2026-03-22 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='co_creators',
            field=models.ManyToManyField(blank=True, related_name='co_created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='printstep',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_steps', to='projects.project'),
        ),
        migrations.AddField(
            model_name='print3ddata',
            name='project',
            field=models.OneToOneField(limit_choices_to={'project_type': 'print_3d'}, on_delete=django.db.models.deletion.CASCADE, related_name='print_3d_data', to='projects.project'),
        ),
        migrations.AddField(
            model_name='project3dfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_3d', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectvideo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='printstep',
            unique_together={('project', 'step_number')},
        ),
    ]
