# Generated by Django 6.0.2 on 2026-03-22 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='print3ddata',
            table='print_3d_data',
        ),
        migrations.AlterModelTable(
            name='printstep',
            table='print_step',
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
        migrations.AlterModelTable(
            name='project3dfile',
            table='project_3d_files',
        ),
        migrations.AlterModelTable(
            name='projectimage',
            table='project_images',
        ),
        migrations.AlterModelTable(
            name='projectvideo',
            table='project_videos',
        ),
    ]
