# Generated by Django 6.0.2 on 2026-04-20

import app.service.UploadService
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_print3ddata_table_alter_printstep_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(upload_to=app.service.UploadService.project_image_upload_to),
        ),
        migrations.AlterField(
            model_name="project3dfile",
            name="file",
            field=models.FileField(upload_to=app.service.UploadService.project_3d_file_upload_to),
        ),
    ]

