# Generated by Django 6.0.2 on 2026-04-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_upload_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('print_3d', 'Impressão 3D'), ('modeling', 'Modelagem'), ('hardware', 'Hardware'), ('software', 'Software')], default='print_3d', max_length=20),
        ),
    ]
